### ISSUE TITLE
EfficientNet training hangs

### ISSUE THREAD

**Issue by nosound2** [pytorch/xla#1081]
## 🐛 Bug

After switching from Resnet50 to EfficientNet-B4b the model stopped training. The same code runs successfully on my local GPU environment and cloud CPU, but hangs on cloud TPU. Specifically, the execution never returns after finishing the first batch. In case of a single TPU device it is inside `xm.mark_step()`. 

The EfficientNet-B4b is the following code, with a custom head (same custom head works with resnet50):
https://github.com/osmr/imgclsmob/blob/master/pytorch/pytorchcv/models/efficientnet.py

## Environment

 - GCP compute engine VM
 - torch_xla nightly updated today
 - TPU v3-8, 24 vCPUs

**Comment by dlibenzi** [comment]
Can you post the code to the custom head?
@zcain117 did some experiments trying to run EfficentNet, and might be able to give more insights...

**Comment by nosound2** [comment]
Thanks for the prompt reply. The custom head is complex, with a lot of staff. But what is important here I think, - that exactly the same custom head works with resnet50 backbone just fine. Moreover, for the first bunch both forward and backward passes succeed, it hangs after that.

**Comment by dlibenzi** [comment]
Hard to debug w/out a repro 😉 
Can you try single core?
```Python
device = xm.xla_device()
model = EfficientNet().to(device)
optimizer = YourChoice(model.parameters(), ...)
...
for sample, target in train_loader:
  sample = sample.to(device)
  target = target.to(device)
  ...
  xm.optimizer_step(optimizer, barrier=True)
  print(torch_xla._XLAC._xla_metrics_report())
```

**Comment by nosound2** [comment]
Is `barrier=True` has same effect as `xm.mark_step()`? I use the later for single core, after `xm.optimizer_step`. This is where it hangs, on `xm.mark_step()`. 

Yes, I understand that it is hard to debug this way. But I also don't have time for debugging it, it is more a report, in the hope that something will click from that limited info alone :). I myself left this architecture for good.

**Comment by dlibenzi** [comment]
If you do not use our background data loader (like in the example above), then `barrier=True` is needed.
Otherwise that is embedded in the iterator.next() call.

**Comment by nosound2** [comment]
I am confused, do you mean `dp.DataParallel`? I don't see data loader in the example above. I use regular pytorch `torch.utils.data.DataLoader`, does it mean I need to add `barrier=True`?

**Comment by dlibenzi** [comment]
Yes, the example above stripped down all the data-loader and multi-core parts, to leave you (aside from the required `xm.optimizer_step(...)`) with a bare bone pytorch programming mode.

If you do not use our `DataParallel` or `ParallelLoader`, you need `barrier=True` in the `xm.optimizer_step()` call, and `xm.mark_step()` in the test loop (which has no optimizer call).

**Comment by dlibenzi** [comment]
Note that `dp.DataParallel` is not a replacement for `torch.utils.data.DataLoader`, but simply a wrapper.
You still use vanilla pytorch data loaders.

**Comment by nosound2** [comment]
Just to be clear, if I use `torch_xla_py.data_parallel.DataParallel` like in the MNIST example I don't need `barrier=True`, is that correct?

**Comment by dlibenzi** [comment]
If you are using (like in the MNIST example), either `dp.DataParallel` or `dp.ParallelLoader`, you are fine.

We never exposed before `dp.ParallelLoader` (the one which send data to device in background, so the upload time and TPU execution can overlap), but now we introduced multi-processing based multi-core, and there (not using `dp.DataParallel` anymore), we use it:

https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py

**Comment by zcain117** [comment]
The issue I ran into with EfficientNet was regarding depthwise convolution, which caused every model to hang where it was used. We had some code changes recently that might help, but I haven't verified if depthwise convolution still hangs or not.

I see your model is using `dwconv3x3_block`, maybe you could try temporarily setting `groups=1` [here](https://github.com/osmr/imgclsmob/blob/master/pytorch/pytorchcv/models/common.py#L461) to see if the model still hangs or not? You may have to throw in a reshape or some other strategy to get the right output shape after the conv step.

**Comment by nosound2** [comment]
Tried setting `groups=1`, same problem persists.

**Comment by brianhhu** [comment]
I was able to train a modified EfficientNet after support for depthwise convolutions was added, see the issue here: #969. The model definition is similar to [this](https://github.com/kuangliu/pytorch-cifar/blob/master/models/efficientnet.py).

**Comment by mruberry** [comment]
Closing since it appears the issue was resolved. @nosound2, was your issue addressed with a newer PyTorch/XLA version?
