### ISSUE TITLE
BERT Training XLA AMP - "No inf checks were recorded for this optimizer" & 50X Slower than native PyTorch

### ISSUE THREAD

**Issue by codeislife99** [pytorch/xla#2918]
## 🐛 Bug
When I run BERT-base with AMP enabled on XLA GPU I get the following error. The same code with CUDA device instead of XLA GPU it works fine. 
```
Traceback (most recent call last):
  File "/pytorch/xla/test/test_train_mp_bert.py", line 186, in <module>
    train_bert(dataset_path, xla_enabled, amp_enabled)
  File "/pytorch/xla/test/test_train_mp_bert.py", line 172, in train_bert
    loss, optimizer = loop_with_amp(model, inputs, sentiment, optimizer, xla_enabled, autocast, scaler)
  File "/pytorch/xla/test/test_train_mp_bert.py", line 91, in loop_with_amp
    scaler.step(optimizer)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/cuda/amp/grad_scaler.py", line 336, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
```
When I run it without AMP enabled, the speed is 50X slower than native PyTorch GPU without AMP 

## To Reproduce
Script: https://github.com/codeislife99/xla/blob/master/test/test_train_mp_bert.py
Dataset:  Easy download -> `wget https://raw.githubusercontent.com/sugi-chan/custom_bert_pipeline/master/IMDB%20Dataset.csv`
Use publicly available docker image for `nightly_3.6_cuda` 

1. Download the dataset using the command
2. Run the script with `xla_enabled= True` and `amp_enabled=True` in the script. To use PyTorch simply change `xla_enabled=False`. To disable amp use `amp_enabled=False` 

Alternatively: Colab Link : https://colab.research.google.com/drive/1Dddkjn2iSsZMW63GcTu1Vhm0NB8ghPkW?usp=sharing  

## Expected behavior

1. For AMP Enabled XLA, I expect it to work smoothly without the error 
2. For AMP Disabled XLA, I don't expect it to be 50X slower. 
## Environment

 - PyTorch XLA GPU - CUDA 10.2

## Environment
For AMP disabled XLA, it seems that the GPU utilization is 0% for 95% for the time unlike the PyTorch case. I strongly believe that this has something to do with the slowdown.

**Comment by zcain117** [comment]
Have you tried the `xmp.spawn` API as shown in this AMP example?
https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist_amp.py

This is how we recommend structuring pytorchXLA training scripts. Without using the `xmp.spawn` API, I worry the other `xm` calls won't work right

I am assuming you also ran something like `export GPU_NUM_DEVICES=1` before training

**Comment by codeislife99** [comment]
Yes for both `xmp.spawn` and the `export GPU_NUM_DEVICES=1` . It doesn't make any difference.

**Comment by zcain117** [comment]
Does this work on TPU?

**Comment by codeislife99** [comment]
No it fails to work even for TPU. I just tried it out.

**Comment by zcain117** [comment]
Thanks for trying that out.

I am confused though - you say it is slow on TPU but also that it fails to work. So does it run slowly for a while and then crash or is the crash immediate?

If it runs for a while, I am curious about the metrics report: https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#get-a-metrics-report

Maybe there is some op that pytorch/XLA doesn't support that is causing slowness and/or crashing

**Comment by codeislife99** [comment]
So it fails to work when AMP is enabled and is slow when AMP is disabled, just like the PT XLA GPU case.

**Comment by zcain117** [comment]
do you have a metrics report for the version that is slow but doesn't crash?

**Comment by codeislife99** [comment]
```<bound method NDFrame.head of                                                   review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]>
xla:1
==> Starting Training
Epoch 0/0
----------
| Training Device=xla:1/0 Epoch=0 Step=0 Loss=0.70362 Rate=2.55 GlobalRate=2.55 Time=23:05:52
Metric: CompileTime
  TotalSamples: 27
  Accumulator: 35s477ms811.760us
  ValueRate: 024ms937.243us / second
  Rate: 0.0182177 / second
  Percentiles: 1%=006ms282.170us; 5%=006ms467.881us; 10%=006ms480.614us; 20%=007ms796.801us; 50%=008ms081.196us; 80%=076ms242.161us; 90%=10s085ms775.577us; 95%=11s190ms959.850us; 99%=12s095ms831.079us
Metric: DeviceLockWait
  TotalSamples: 27
  Accumulator: 072.945us
  ValueRate: 000.050us / second
  Rate: 0.0183456 / second
  Percentiles: 1%=001.228us; 5%=001.412us; 10%=001.670us; 20%=002.284us; 50%=002.834us; 80%=003.195us; 90%=003.514us; 95%=003.697us; 99%=003.746us
Metric: ExecuteTime
  TotalSamples: 27
  Accumulator: 560ms475.875us
  ValueRate: 378.130us / second
  Rate: 0.0182158 / second
  Percentiles: 1%=002ms371.105us; 5%=002ms436.629us; 10%=002ms454.721us; 20%=003ms665.891us; 50%=003ms882.050us; 80%=009ms218.821us; 90%=150ms469.441us; 95%=154ms759.946us; 99%=166ms529.295us
Metric: InboundData
  TotalSamples: 27
  Accumulator: 140.00B
  ValueRate: 0.09B / second
  Rate: 0.0182158 / second
  Percentiles: 1%=1.00B; 5%=1.00B; 10%=1.00B; 20%=1.00B; 50%=4.00B; 80%=4.00B; 90%=12.00B; 95%=12.00B; 99%=45.00B
Metric: InputOutputAliasCount
  TotalSamples: 24
  Accumulator: 25.00
  ValueRate: 0.02 / second
  Rate: 0.0163069 / second
  Percentiles: 1%=1.00; 5%=1.00; 10%=1.00; 20%=1.00; 50%=1.00; 80%=1.00; 90%=1.00; 95%=1.00; 99%=2.00
Metric: IrValueTensorToXlaData
  TotalSamples: 615
  Accumulator: 15s699ms251.278us
  ValueRate: 010ms000.559us / second
  Rate: 0.418412 / second
  Percentiles: 1%=001ms295.594us; 5%=001ms458.477us; 10%=002ms579.901us; 20%=002ms714.226us; 50%=002ms052.248us; 80%=026ms885.283us; 90%=096ms362.632us; 95%=097ms208.235us; 99%=102ms865.996us
Metric: OutboundData
  TotalSamples: 629
  Accumulator: 1.22GB
  ValueRate: 871.98KB / second
  Rate: 0.427399 / second
  Percentiles: 1%=4.00B; 5%=3.00KB; 10%=3.00KB; 20%=3.00KB; 50%=3.00KB; 80%=2.25MB; 90%=9.00MB; 95%=9.00MB; 99%=9.00MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 38
  Accumulator: 02s360ms660.566us
  ValueRate: 002ms591.975us / second
  Rate: 0.0256372 / second
  Percentiles: 1%=675.635us; 5%=708.634us; 10%=865.888us; 20%=943.633us; 50%=001ms129.531us; 80%=202ms868.928us; 90%=232ms285.397us; 95%=351ms999.950us; 99%=404ms310.220us
Metric: TensorsGraphSize
  TotalSamples: 27
  Accumulator: 10234.00
  ValueRate: 6.91 / second
  Rate: 0.0182177 / second
  Percentiles: 1%=3.00; 5%=3.00; 10%=3.00; 20%=3.00; 50%=5.00; 80%=6.00; 90%=3223.00; 95%=3375.00; 99%=3527.00
Metric: TransferFromServerTime
  TotalSamples: 27
  Accumulator: 082ms141.971us
  ValueRate: 055.418us / second
  Rate: 0.0182158 / second
  Percentiles: 1%=001ms371.930us; 5%=001ms418.724us; 10%=002ms542.640us; 20%=002ms582.277us; 50%=002ms791.652us; 80%=002ms231.236us; 90%=009ms797.708us; 95%=009ms408.520us; 99%=010ms073.153us
Metric: TransferToServerTime
  TotalSamples: 629
  Accumulator: 15s732ms508.719us
  ValueRate: 010ms009.937us / second
  Rate: 0.4274 / second
  Percentiles: 1%=001ms245.277us; 5%=001ms446.548us; 10%=002ms567.357us; 20%=002ms702.467us; 50%=002ms039.692us; 80%=026ms823.304us; 90%=096ms166.012us; 95%=097ms157.393us; 99%=102ms856.959us
Metric: TransferToServerTransformTime
  TotalSamples: 629
  Accumulator: 414ms378.650us
  ValueRate: 281.566us / second
  Rate: 0.427399 / second
  Percentiles: 1%=109.761us; 5%=127.806us; 10%=138.186us; 20%=154.570us; 50%=189.945us; 80%=715.622us; 90%=002ms222.961us; 95%=002ms302.634us; 99%=003ms534.121us
Counter: CreateCompileHandles
  Value: 27
Counter: CreateDataHandles
  Value: 657
Counter: CreateXlaTensor
  Value: 11349
Counter: DestroyDataHandles
  Value: 233
Counter: DestroyXlaTensor
  Value: 10536
Counter: DeviceDataCacheMiss
  Value: 13
Counter: ReleaseDataHandles
  Value: 233
Counter: UncachedCompile
  Value: 27
Counter: XRTAllocateFromTensor_Empty
  Value: 16
Counter: XrtCompile_Empty
  Value: 1152
Counter: XrtExecuteChained_Empty
  Value: 1152
Counter: XrtExecute_Empty
  Value: 1152
Counter: XrtMemoryInfo_Empty
  Value: 1152
Counter: XrtRead_Empty
  Value: 1152
Counter: XrtReleaseAllocationHandle_Empty
  Value: 1152
Counter: XrtReleaseCompileHandle_Empty
  Value: 1152
Counter: XrtSessionCount
  Value: 10
Counter: XrtSubTuple_Empty
  Value: 1152
Counter: aten::_local_scalar_dense
  Value: 23
Counter: aten::masked_select
  Value: 1
Counter: xla::_copy_from
  Value: 1132
Counter: xla::_log_softmax
  Value: 4
Counter: xla::_log_softmax_backward_data
  Value: 4
Counter: xla::_softmax
  Value: 48
Counter: xla::_softmax_backward_data
  Value: 48
Counter: xla::_unsafe_view
  Value: 384
Counter: xla::abs
  Value: 2
Counter: xla::add
  Value: 340
Counter: xla::add_
  Value: 493
Counter: xla::addcmul
  Value: 100
Counter: xla::addmm
  Value: 8
Counter: xla::as_strided
  Value: 614
Counter: xla::bernoulli_
  Value: 152
Counter: xla::bitwise_and_out
  Value: 1
Counter: xla::bmm
  Value: 288
Counter: xla::ceil
  Value: 9
Counter: xla::div
  Value: 97
Counter: xla::div_
  Value: 152
Counter: xla::embedding
  Value: 12
Counter: xla::embedding_dense_backward
  Value: 12
Counter: xla::empty
  Value: 1298
Counter: xla::empty_strided
  Value: 614
Counter: xla::eq
  Value: 1
Counter: xla::expand
  Value: 192
Counter: xla::fill_
  Value: 12
Counter: xla::gelu
  Value: 48
Counter: xla::gelu_backward
  Value: 48
Counter: xla::gt
  Value: 2
Counter: xla::index_select
  Value: 12
Counter: xla::masked_select
  Value: 1
Counter: xla::max
  Value: 1
Counter: xla::min
  Value: 1
Counter: xla::mm
  Value: 880
Counter: xla::mul
  Value: 711
Counter: xla::native_batch_norm
  Value: 100
Counter: xla::native_batch_norm_backward
  Value: 100
Counter: xla::ne
  Value: 11
Counter: xla::nll_loss_backward
  Value: 4
Counter: xla::nll_loss_forward
  Value: 4
Counter: xla::permute
  Value: 384
Counter: xla::reciprocal
  Value: 1
Counter: xla::rsub
  Value: 4
Counter: xla::select
  Value: 11
Counter: xla::slice
  Value: 24
Counter: xla::sum
  Value: 501
Counter: xla::t
  Value: 1184
Counter: xla::tanh
  Value: 4
Counter: xla::tanh_backward
  Value: 4
Counter: xla::transpose
  Value: 288
Counter: xla::unbind
  Value: 2
Counter: xla::unsqueeze
  Value: 8
Counter: xla::view
  Value: 3245
Counter: xla::zero_
  Value: 12
Metric: XrtAllocateFromTensor
  TotalSamples: 629
  Accumulator: 923ms982.712us
  Mean: 001ms467.381us
  StdDev: 005ms969.700us
  Rate: 0.427409 / second
  Percentiles: 25%=395.062us; 50%=547.445us; 80%=002ms673.660us; 90%=003ms314.630us; 95%=004ms703.699us; 99%=008ms664.724us
Metric: XrtCompile
  TotalSamples: 27
  Accumulator: 35s165ms727.089us
  Mean: 01s302ms397.300us
  StdDev: 03s490ms625.758us
  Rate: 0.0182181 / second
  Percentiles: 25%=005ms353.712us; 50%=006ms264.947us; 80%=008ms109.819us; 90%=10s065ms254.616us; 95%=11s171ms671.107us; 99%=12s064ms960.876us
Metric: XrtExecute
  TotalSamples: 27
  Accumulator: 489ms577.999us
  Mean: 018ms095.481us
  StdDev: 047ms009.114us
  Rate: 0.0182161 / second
  Percentiles: 25%=001ms339.315us; 50%=001ms429.529us; 80%=002ms813.524us; 90%=149ms545.438us; 95%=152ms926.529us; 99%=153ms661.782us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 28
  Accumulator: 016ms940.356us
  Mean: 569.298us
  StdDev: 115.996us
  Rate: 0.0188908 / second
  Percentiles: 25%=491.379us; 50%=551.959us; 80%=684.422us; 90%=734.375us; 95%=749.440us; 99%=884.772us
Metric: XrtReleaseAllocation
  TotalSamples: 38
  Accumulator: 002ms780.317us
  Mean: 046.850us
  StdDev: 064.375us
  Rate: 0.0256377 / second
  Percentiles: 25%=019.981us; 50%=025.191us; 80%=047.437us; 90%=078.176us; 95%=264.033us; 99%=312.255us```

**Comment by zcain117** [comment]
Thanks for sharing that.  I see in the report that the model is calling to `aten::masked_select`

I know in the past this has caused problems for models, such as: https://github.com/pytorch/xla/issues/1522#issuecomment-576248833

@JackCaoG might know best about the latest `aten::masked_select` status. Maybe it is not an issue anymore or maybe there is some workaround

**Comment by codeislife99** [comment]
Out of curiosity, how did you know that `aten::masked_select` is the problem, is this from your knowledge of previous issues ?
I am also noticing that the GPU utilization is at 0% for 95% of the time. I thought this might be due to the dataloader so I switched to a different loader with this change `train_device_loader = pl.MpDeviceLoader(dataloaders_dict['train'], device)`. This gave rise to a new error: 
```2021-04-27 23:52:22.313348: W    2044 tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xrt_compile_ops.cc:220 : Internal: Seen floating point types of different precisions in %batch-norm-grad.5822 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4834, f32[8192]{0} %broadcast.5804, f32[8192]{0} %get-tuple-element.4837, f32[8192]{0} %subtract.5821, f64[1,8192,768]{2,1,0} %reshape.5814), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
2021-04-27 23:52:22.428544: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] StackTrace:
2021-04-27 23:52:22.428617: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** Begin stack trace ***
2021-04-27 23:52:22.428642: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::ReportComputationError(tensorflow::Status const&, absl::lts_2020_02_25::Span<xla::XlaComputation const* const>, absl::lts_2020_02_25::Span<xla::Shape const* const>)
2021-04-27 23:52:22.428661: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::XrtComputationClient::CheckCompileStatus(tensorflow::Status const&, std::vector<xla::ComputationClient::CompileInstance, std::allocator<xla::ComputationClient::CompileInstance> > const&, xla::XrtComputationClient::SessionWork const&)
2021-04-27 23:52:22.428677: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-04-27 23:52:22.428693: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::MultiWait::Complete(std::function<void ()> const&)
2021-04-27 23:52:22.428710: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-04-27 23:52:22.428725: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-04-27 23:52:22.428747: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-04-27 23:52:22.428763: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        clone
2021-04-27 23:52:22.428782: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** End stack trace ***
2021-04-27 23:52:22.428799: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-04-27 23:52:22.428821: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] Status: Internal: From /job:localservice/replica:0/task:0:
2021-04-27 23:52:22.428843: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 2 root error(s) found.
2021-04-27 23:52:22.428861: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   (0) Internal: Seen floating point types of different precisions in %batch-norm-grad.5822 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4834, f32[8192]{0} %broadcast.5804, f32[8192]{0} %get-tuple-element.4837, f32[8192]{0} %subtract.5821, f64[1,8192,768]{2,1,0} %reshape.5814), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
2021-04-27 23:52:22.428887: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]         [[{{node XRTCompile}}]]
2021-04-27 23:52:22.428903: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   (1) Internal: Seen floating point types of different precisions in %batch-norm-grad.5822 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4834, f32[8192]{0} %broadcast.5804, f32[8192]{0} %get-tuple-element.4837, f32[8192]{0} %subtract.5821, f64[1,8192,768]{2,1,0} %reshape.5814), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
2021-04-27 23:52:22.428926: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]         [[{{node XRTCompile}}]]
2021-04-27 23:52:22.428948: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]         [[XRTCompile_G6]]
2021-04-27 23:52:22.428969: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 0 successful operations.
2021-04-27 23:52:22.428992: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 0 derived errors ignored.
2021-04-27 23:52:22.429011: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88] Recent warning and error logs:
2021-04-27 23:52:22.429026: E    2080 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   OP_REQUIRES failed at xrt_compile_ops.cc:220 : Internal: Seen floating point types of different precisions in %batch-norm-grad.5822 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4834, f32[8192]{0} %broadcast.5804, f32[8192]{0} %get-tuple-element.4837, f32[8192]{0} %subtract.5821, f64[1,8192,768]{2,1,0} %reshape.5814), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
Traceback (most recent call last):
  File "/pytorch/xla/test/test_train_mp_bert.py", line 202, in <module>
    train_bert(dataset_path, xla_enabled, amp_enabled)
  File "/pytorch/xla/test/test_train_mp_bert.py", line 175, in train_bert
    for step, (inputs, sentiment) in enumerate(dataloaders_dict['train']):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py", line 34, in __next__
    return self.next()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py", line 46, in next
    xm.mark_step()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Internal: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) Internal: Seen floating point types of different precisions in %batch-norm-grad.5822 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4834, f32[8192]{0} %broadcast.5804, f32[8192]{0} %get-tuple-element.4837, f32[8192]{0} %subtract.5821, f64[1,8192,768]{2,1,0} %reshape.5814), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
         [[{{node XRTCompile}}]]
  (1) Internal: Seen floating point types of different precisions in %batch-norm-grad.5822 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4834, f32[8192]{0} %broadcast.5804, f32[8192]{0} %get-tuple-element.4837, f32[8192]{0} %subtract.5821, f64[1,8192,768]{2,1,0} %reshape.5814), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
         [[{{node XRTCompile}}]]
         [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at xrt_compile_ops.cc:220 : Internal: Seen floating point types of different precisions in %batch-norm-grad.5822 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4834, f32[8192]{0} %broadcast.5804, f32[8192]{0} %get-tuple-element.4837, f32[8192]{0} %subtract.5821, f64[1,8192,768]{2,1,0} %reshape.5814), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.```
  Its unclear to me why this error didn't show up when not using the parallel dataloader.

**Comment by JackCaoG** [comment]
We have some debug tips on https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#understand-the-metrics-report.

There are couple things show up in this metric report
```
Metric: CompileTime
  TotalSamples: 27
  Accumulator: 35s477ms811.760us
  ValueRate: 024ms937.243us / second
  Rate: 0.0182177 / second
  Percentiles: 1%=006ms282.170us; 5%=006ms467.881us; 10%=006ms480.614us; 20%=007ms796.801us; 50%=008ms081.196us; 80%=076ms242.161us; 90%=10s085ms775.577us; 95%=11s190ms959.850us; 99%=12s095ms831.079us
Metric: ExecuteTime
  TotalSamples: 27
  Accumulator: 560ms475.875us
  ValueRate: 378.130us / second
  Rate: 0.0182158 / second
```

There are 27 compiles and 27 execute. This means the graph keeps being updated and xla needs to recompile the graph for every execution. Please check https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#known-performance-caveats. To optimize the speed, we expect graph stabilize pretty quick (1 compile, many exeuction).

For masked_select, you can check https://github.com/pytorch/xla/issues/2602. 
```
Counter: aten::masked_select
  Value: 1
```
This counter is a sign that we fallback to CPU which will also degrade the speed. You can enable the experiment `masked_select` by  `XLA_EXPERIMENTAL="masked_select"` but the support of this op is non-intuitive, I explained in the other thread. I will try to workaround this dynamic op to avoid recompilation.

Last one is 
```
Counter: aten::_local_scalar_dense
  Value: 23
```
I am suspecting you are accessing the tensor value(print, if statment and etc..) during the epoch which resulted in early evaluation of the graph and hurts the performance.

**Comment by codeislife99** [comment]
While I am still looking into this slowdown cause, do you have any ideas around why the AMP run failed outright ?

**Comment by JackCaoG** [comment]
Suspecting it is something similar to https://github.com/PyTorchLightning/pytorch-lightning/issues/4524#L1229

**Comment by codeislife99** [comment]
I read that thread when I first came across the problem , but it doesn't have any fixes or solutions. My code is pretty simple and I am not using PyTorch Lightning, and I still see this error. Also I DON'T see this error when I use regular pytorch but only when I use XLA. This means that something must be wrong with the latter (either in my script or in the library itself)

**Comment by codeislife99** [comment]
Hi, I thoroughly checked my scripts, and to me it doesn't appear that I am doing any of the pitfalls mentioned in the section. I am using the model directly provided by hugging-face which is supported on TPU as well. It seems that the GPU utilization is high only for a very small period of time which might be related to the slowdown. So I tried to use the `pl.MpDeviceLoader` and when I do that it throws a completely new error, 
```| Training Device=xla:0/0 Epoch=0 Step=0 Loss=0.67254 Rate=1.39 GlobalRate=1.39 Time=12:10:23
2021-05-06 12:10:23.330647: W    5806 tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xrt_compile_ops.cc:220 : Internal: Seen floating point types of different precisions in %batch-norm-grad.5797 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4809, f32[8192]{0} %broadcast.5779, f32[8192]{0} %get-tuple-element.4812, f32[8192]{0} %subtract.5796, f64[1,8192,768]{2,1,0} %reshape.5789), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
2021-05-06 12:10:23.441382: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] StackTrace:
2021-05-06 12:10:23.441445: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** Begin stack trace ***
2021-05-06 12:10:23.441474: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::ReportComputationError(tensorflow::Status const&, absl::lts_2020_02_25::Span<xla::XlaComputation const* const>, absl::lts_2020_02_25::Span<xla::Shape const* const>)
2021-05-06 12:10:23.441483: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::XrtComputationClient::CheckCompileStatus(tensorflow::Status const&, std::vector<xla::ComputationClient::CompileInstance, std::allocator<xla::ComputationClient::CompileInstance> > const&, xla::XrtComputationClient::SessionWork const&)
2021-05-06 12:10:23.441496: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-05-06 12:10:23.441507: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::MultiWait::Complete(std::function<void ()> const&)
2021-05-06 12:10:23.441517: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-05-06 12:10:23.441527: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-05-06 12:10:23.441537: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-05-06 12:10:23.441550: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        clone
2021-05-06 12:10:23.441565: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** End stack trace ***
2021-05-06 12:10:23.441582: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2021-05-06 12:10:23.441597: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] Status: Internal: From /job:localservice/replica:0/task:0:
2021-05-06 12:10:23.441612: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 2 root error(s) found.
2021-05-06 12:10:23.441624: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   (0) Internal: Seen floating point types of different precisions in %batch-norm-grad.5797 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4809, f32[8192]{0} %broadcast.5779, f32[8192]{0} %get-tuple-element.4812, f32[8192]{0} %subtract.5796, f64[1,8192,768]{2,1,0} %reshape.5789), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
2021-05-06 12:10:23.441637: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]         [[{{node XRTCompile}}]]
2021-05-06 12:10:23.441647: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   (1) Internal: Seen floating point types of different precisions in %batch-norm-grad.5797 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4809, f32[8192]{0} %broadcast.5779, f32[8192]{0} %get-tuple-element.4812, f32[8192]{0} %subtract.5796, f64[1,8192,768]{2,1,0} %reshape.5789), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
2021-05-06 12:10:23.441658: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]         [[{{node XRTCompile}}]]
2021-05-06 12:10:23.441668: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]         [[XRTCompile_G6]]
2021-05-06 12:10:23.441678: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 0 successful operations.
2021-05-06 12:10:23.441690: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 0 derived errors ignored.
2021-05-06 12:10:23.441704: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88] Recent warning and error logs:
2021-05-06 12:10:23.441720: E    5946 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   OP_REQUIRES failed at xrt_compile_ops.cc:220 : Internal: Seen floating point types of different precisions in %batch-norm-grad.5797 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4809, f32[8192]{0} %broadcast.5779, f32[8192]{0} %get-tuple-element.4812, f32[8192]{0} %subtract.5796, f64[1,8192,768]{2,1,0} %reshape.5789), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
Traceback (most recent call last):
  File "/pytorch/xla/test/test_train_mp_bert.py", line 219, in <module>
    xmp.spawn(_mp_fn, nprocs=1)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 386, in spawn
    _start_fn(0, pf_cfg, fn, args)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    fn(gindex, *args)
  File "/pytorch/xla/test/test_train_mp_bert.py", line 211, in _mp_fn
    train_bert(dataset_path, xla_enabled, amp_enabled)
  File "/pytorch/xla/test/test_train_mp_bert.py", line 193, in train_bert
    for step, (inputs, sentiment) in enumerate(train_device_loader):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py", line 34, in __next__
    return self.next()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py", line 46, in next
    xm.mark_step()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Internal: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) Internal: Seen floating point types of different precisions in %batch-norm-grad.5797 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4809, f32[8192]{0} %broadcast.5779, f32[8192]{0} %get-tuple-element.4812, f32[8192]{0} %subtract.5796, f64[1,8192,768]{2,1,0} %reshape.5789), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
         [[{{node XRTCompile}}]]
  (1) Internal: Seen floating point types of different precisions in %batch-norm-grad.5797 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4809, f32[8192]{0} %broadcast.5779, f32[8192]{0} %get-tuple-element.4812, f32[8192]{0} %subtract.5796, f64[1,8192,768]{2,1,0} %reshape.5789), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.
         [[{{node XRTCompile}}]]
         [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at xrt_compile_ops.cc:220 : Internal: Seen floating point types of different precisions in %batch-norm-grad.5797 = (f32[1,8192,768]{2,1,0}, f32[8192]{0}, f32[8192]{0}) batch-norm-grad(f32[1,8192,768]{2,1,0} %reshape.4809, f32[8192]{0} %broadcast.5779, f32[8192]{0} %get-tuple-element.4812, f32[8192]{0} %subtract.5796, f64[1,8192,768]{2,1,0} %reshape.5789), epsilon=1e-12, feature_index=1, but mixed precision is disallowed.```

Other than that, I moved all of the `__getitem__` code in dataloader in `__init__` meaning I loaded the entire data so that it doesn't become a bottleneck. The PyTorch version got 2X faster while the XLA version was at the same speed as before. I am unable to figure out why that is as well. 


TLDR: I am still at the original issue after going through the model code and dataloaders etc. with XLA but managed to double my native PyTorch speed, and XLA stayed at the same rate unfortunately. Plus got some new errors in floating point precision match

**Comment by codeislife99** [comment]
I have also updated the code I am using so all of this is reproducible.

**Comment by codeislife99** [comment]
@yaochengji Do you mind sharing the BERT codebase/script you used to run it successfully with good performance , I am facing a lot of issues ? Thanks.

**Comment by yaochengji** [comment]
@codeislife99 I'm sorry I cannot because of the company regulation.

**Comment by yaochengji** [comment]
https://github.com/codeislife99/xla/blob/9f3b7f2b8d60ee4e2e10548ba2470aff3ca170cd/test/test_train_mp_bert.py#L177
I think you should swap L177 and L179.

**Comment by yaochengji** [comment]
For the `Internal: Seen floating point types of different precisions in` issue, I also find that there's something wrong when the pytorch `autocast` logic deals with `fp64`. A workaround is to change all `fp64` to `fp32`.

**Comment by codeislife99** [comment]
Wow @yaochengji - Swapping those lines solved the optimizer issue I was encountering with AMP. Now its 20% faster than native pytorch CUDA with AMP enabled. I never would have even thought it would be so trivial. Do you know what changes internally when these two lines are swapped ?? 
cc: @JackCaoG

**Comment by codeislife99** [comment]
I will try the fp64 to fp32 and see if things change.

**Comment by codeislife99** [comment]
Another question, I have is, you said that you weren't able to see a speedup for BERT, but I was able to see 20% for this specific model. Most probably we are using different BERT models. Is your model heavier or if that's something you cannot disclose that's fine too.

**Comment by codeislife99** [comment]
Another question, I have is, you said that you weren't able to see a speedup for BERT, but I was able to see 30% slowdown for this specific model. Most probably we are using different BERT models. Is your model heavier or if that's something you cannot disclose that's fine too.

**Comment by yaochengji** [comment]
> Wow @yaochengji - Swapping those lines solved the optimizer issue I was encountering with AMP. I never would have even thought it would be so trivial. Do you know what changes internally when these two lines are swapped ??
> cc: @JackCaoG

The previous version fails because optimizer is constructed with non-xla device model.

**Comment by yaochengji** [comment]
> Another question, I have is, you said that you weren't able to see a speedup for BERT, but I was able to see 30% slowdown for this specific model. Most probably we are using different BERT models. Is your model heavier or if that's something you cannot disclose that's fine too.

The model I tested before was written by others, hence what I know is only that it is a bert-like model. It is possible different models has different performances. For the 30% slowdown, I suppose you could use https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#understand-the-metrics-report. to make sure there's only one computing graph to maximize the ability of pytorch/xla.

**Comment by codeislife99** [comment]
> The previous version fails because optimizer is constructed with non-xla device model.

Yeah, I see that, but when we switch from CPU <-> GPU in native PyTorch, even though optimizer is constructed with CPU model, it doesn't have the same errors. So what changes with XLA was what I wanted to ask

**Comment by codeislife99** [comment]
> > Another question, I have is, you said that you weren't able to see a speedup for BERT, but I was able to see 30% slowdown for this specific model. Most probably we are using different BERT models. Is your model heavier or if that's something you cannot disclose that's fine too.
> 
> The model I tested before was written by others, hence what I know is only that it is a bert-like model. It is possible different models has different performances. For the 30% slowdown, I suppose you could use https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#understand-the-metrics-report. to make sure there's only one computing graph to maximize the ability of pytorch/xla.

Yeah now that I am able to get it working with some reasonable speed, I will do a thorough analysis. Just wanted to get a high level idea of what your model looked like,  so thanks for sharing that information :)

**Comment by codeislife99** [comment]
These are the metrics that I generated. I see that `aten::masked_select` is not present anymore and also that compilation is occuring very rarely and only occurred mostly initially. Trying to find out what other reasons might be for the slowdown.
`Metric: CompileTime
  TotalSamples: 5
  Accumulator: 04m19s324ms429.976us
  ValueRate: 964ms427.143us / second
  Rate: 0.018595 / second
  Percentiles: 1%=073ms863.719us; 5%=073ms863.719us; 10%=073ms863.719us; 20%=079ms742.750us; 50%=01m25s205ms880.592us; 80%=01m29s550ms258.393us; 90%=01m29s550ms258.393us; 95%=01m29s550ms258.393us; 99%=01m29s550ms258.393us
Metric: DeviceLockWait
  TotalSamples: 668
  Accumulator: 30s817ms698.991us
  ValueRate: 100ms158.998us / second
  Rate: 2.24392 / second
  Percentiles: 1%=000.000us; 5%=000.000us; 10%=002.510us; 20%=002.730us; 50%=003.047us; 80%=006ms915.825us; 90%=229ms012.009us; 95%=229ms484.265us; 99%=231ms554.258us
Metric: ExecuteTime
  TotalSamples: 265
  Accumulator: 30s997ms249.907us
  ValueRate: 101ms798.174us / second
  Rate: 0.890466 / second
  Percentiles: 1%=793.340us; 5%=843.330us; 10%=866.130us; 20%=908.552us; 50%=007ms355.670us; 80%=230ms873.669us; 90%=230ms243.568us; 95%=231ms632.003us; 99%=235ms077.145us
Metric: InboundData
  TotalSamples: 264
  Accumulator: 1.03KB
  ValueRate: 4.98B / second
  Rate: 1.24588 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=4.00B; 50%=4.00B; 80%=4.00B; 90%=4.00B; 95%=4.00B; 99%=4.00B
Metric: InputOutputAliasCount
  TotalSamples: 5
  Accumulator: 815.00
  ValueRate: 4.52 / second
  Rate: 0.0277155 / second
  Percentiles: 1%=2.00; 5%=2.00; 10%=2.00; 20%=202.00; 50%=203.00; 80%=205.00; 90%=205.00; 95%=205.00; 99%=205.00
Metric: IrValueTensorToXlaData
  TotalSamples: 202
  Accumulator: 852ms965.924us
  ValueRate: 02s857ms416.297us / second
  Rate: 440.391 / second
  Percentiles: 1%=616.843us; 5%=685.056us; 10%=713.481us; 20%=764.573us; 50%=862.712us; 80%=003ms510.837us; 90%=007ms583.835us; 95%=007ms857.153us; 99%=009ms586.506us
Metric: OutboundData
  TotalSamples: 378
  Accumulator: 426.25MB
  ValueRate: 1.43MB / second
  Rate: 1.26752 / second
  Percentiles: 1%=4.00B; 5%=8.00B; 10%=8.00B; 20%=8.00B; 50%=3.00KB; 80%=257.00KB; 90%=2.25MB; 95%=9.00MB; 99%=9.00MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 7203
  Accumulator: 04s608ms173.716us
  ValueRate: 082ms346.416us / second
  Rate: 189.755 / second
  Percentiles: 1%=235.252us; 5%=259.958us; 10%=280.681us; 20%=309.996us; 50%=386.384us; 80%=528.518us; 90%=652.008us; 95%=770.035us; 99%=981.160us
Metric: TensorsGraphSize
  TotalSamples: 265
  Accumulator: 823191.00
  ValueRate: 2766.06 / second
  Rate: 0.890445 / second
  Percentiles: 1%=4.00; 5%=4.00; 10%=4.00; 20%=4.00; 50%=1010.00; 80%=6233.00; 90%=6233.00; 95%=6233.00; 99%=6233.00
Metric: TransferFromServerTime
  TotalSamples: 264
  Accumulator: 215ms843.754us
  ValueRate: 001ms013.903us / second
  Rate: 1.24588 / second
  Percentiles: 1%=420.575us; 5%=449.417us; 10%=470.192us; 20%=507.768us; 50%=574.095us; 80%=661.856us; 90%=712.194us; 95%=848.891us; 99%=006ms420.298us
Metric: TransferToServerTime
  TotalSamples: 378
  Accumulator: 01s075ms091.146us
  ValueRate: 004ms609.205us / second
  Rate: 1.26899 / second
  Percentiles: 1%=419.553us; 5%=441.071us; 10%=473.527us; 20%=523.983us; 50%=788.446us; 80%=002ms274.624us; 90%=003ms387.714us; 95%=007ms720.105us; 99%=013ms082.406us
Metric: TransferToServerTransformTime
  TotalSamples: 378
  Accumulator: 300ms430.715us
  ValueRate: 001ms007.411us / second
  Rate: 1.26752 / second
  Percentiles: 1%=042.586us; 5%=056.183us; 10%=063.019us; 20%=068.816us; 50%=106.074us; 80%=482.995us; 90%=001ms397.007us; 95%=005ms835.231us; 99%=005ms127.945us
Counter: CachedCompile
  Value: 260
Counter: CreateCompileHandles
  Value: 5
Counter: CreateDataHandles
  Value: 27887
Counter: CreateXlaTensor
  Value: 383222
Counter: DestroyDataHandles
  Value: 27454
Counter: DestroyXlaTensor
  Value: 382798
Counter: DeviceDataCacheMiss
  Value: 9
Counter: MarkStep
  Value: 404
Counter: ReleaseDataHandles
  Value: 27454
Counter: UncachedCompile
  Value: 5
Counter: XRTAllocateFromTensor_Empty
  Value: 25
Counter: XrtCompile_Empty
  Value: 128
Counter: XrtExecuteChained_Empty
  Value: 128
Counter: XrtExecute_Empty
  Value: 128
Counter: XrtMemoryInfo_Empty
  Value: 128
Counter: XrtRead_Empty
  Value: 128
Counter: XrtReleaseAllocationHandle_Empty
  Value: 128
Counter: XrtReleaseCompileHandle_Empty
  Value: 128
Counter: XrtSessionCount
  Value: 10
Counter: XrtSubTuple_Empty
  Value: 128
Counter: aten::_local_scalar_dense
  Value: 264
Counter: xla::_amp_foreach_non_finite_check_and_unscale_
  Value: 132
Counter: xla::_amp_update_scale
  Value: 132
Counter: xla::_copy_from
  Value: 67522
Counter: xla::_log_softmax
  Value: 132
Counter: xla::_log_softmax_backward_data
  Value: 132
Counter: xla::_softmax
  Value: 1584
Counter: xla::_softmax_backward_data
  Value: 1584
Counter: xla::_unsafe_view
  Value: 12672
Counter: xla::add
  Value: 11220
Counter: xla::add_
  Value: 35967
Counter: xla::addcmul
  Value: 3300
Counter: xla::addmm
  Value: 264
Counter: xla::as_strided
  Value: 202
Counter: xla::bernoulli_
  Value: 5016
Counter: xla::bmm
  Value: 9504
Counter: xla::div
  Value: 3168
Counter: xla::div_
  Value: 5016
Counter: xla::embedding
  Value: 396
Counter: xla::embedding_dense_backward
  Value: 396
Counter: xla::empty
  Value: 73068
Counter: xla::empty_strided
  Value: 202
Counter: xla::expand
  Value: 6336
Counter: xla::fill_
  Value: 398
Counter: xla::gelu
  Value: 1584
Counter: xla::gelu_backward
  Value: 1584
Counter: xla::index_select
  Value: 396
Counter: xla::mm
  Value: 29040
Counter: xla::mul
  Value: 23628
Counter: xla::native_batch_norm
  Value: 3300
Counter: xla::native_batch_norm_backward
  Value: 3300
Counter: xla::nll_loss_backward
  Value: 132
Counter: xla::nll_loss_forward
  Value: 132
Counter: xla::permute
  Value: 12672
Counter: xla::reciprocal
  Value: 132
Counter: xla::rsub
  Value: 132
Counter: xla::select
  Value: 264
Counter: xla::slice
  Value: 792
Counter: xla::sum
  Value: 16632
Counter: xla::t
  Value: 39072
Counter: xla::tanh
  Value: 132
Counter: xla::tanh_backward
  Value: 132
Counter: xla::transpose
  Value: 9504
Counter: xla::unsqueeze
  Value: 264
Counter: xla::view
  Value: 107052
Counter: xla::zero_
  Value: 26727
Metric: XrtAllocateFromTensor
  TotalSamples: 623
  Accumulator: 507ms634.379us
  Mean: 813.217us
  StdDev: 014ms670.128us
  Rate: 2.09148 / second
  Percentiles: 25%=064.784us; 50%=112.359us; 80%=316.647us; 90%=404.975us; 95%=524.863us; 99%=001ms136.745us
Metric: XrtCompile
  TotalSamples: 5
  Accumulator: 04m19s126ms412.420us
  Mean: 52s825ms282.484us
  StdDev: 42s280ms044.459us
  Rate: 0.018595 / second
  Percentiles: 25%=068ms594.492us; 50%=01m25s151ms039.673us; 80%=01m28s491ms875.726us; 90%=01m28s491ms875.726us; 95%=01m28s491ms875.726us; 99%=01m28s491ms875.726us
Metric: XrtExecute
  TotalSamples: 265
  Accumulator: 30s722ms897.375us
  Mean: 112ms158.103us
  StdDev: 114ms856.120us
  Rate: 0.890465 / second
  Percentiles: 25%=196.630us; 50%=001ms153.727us; 80%=229ms883.588us; 90%=229ms170.808us; 95%=229ms448.404us; 99%=231ms481.682us
Metric: XrtReadLiteral
  TotalSamples: 264
  Accumulator: 021ms338.543us
  Mean: 080.828us
  StdDev: 022.179us
  Rate: 1.24588 / second
  Percentiles: 25%=066.825us; 50%=074.994us; 80%=095.842us; 90%=111.440us; 95%=125.058us; 99%=141.474us
Metric: XrtReleaseAllocation
  TotalSamples: 7203
  Accumulator: 164ms621.541us
  Mean: 022.758us
  StdDev: 027.790us
  Rate: 189.755 / second
  Percentiles: 25%=009.712us; 50%=013.632us; 80%=030.054us; 90%=049.913us; 95%=071.566us; 99%=139.176us`

**Comment by codeislife99** [comment]
@JackCaoG @yaochengji Is it really possible to eliminate this `aten::_local_scalar_dense` given that it is coming from `GradScaler()` or should I just look for alternate areas of slowdown?

**Comment by anijain2305** [comment]
Name | Num_calls | Total time (ms) | Percentage | Acc Percentage
-- | -- | -- | -- | --
CompileTime | 5 | 4017533.72 | 39.76 | 39.76
DeviceLockWait | 3248 | 3056176.38 | 30.25 | 70.01
ExecuteTime | 1601 | 3002535.26 | 29.72 | 99.73
ReleaseDataHandlesTime | 40632 | 21675.14 | 0.21 | 99.94
TransferToServerTime | 1211 | 2493.14 | 0.02 | 99.97
IrValueTensorToXlaData | 202 | 1446.48 | 0.01 | 99.98
TransferToServerTransformTime | 1211 | 1018.78 | 0.01 | 99.99
TransferFromServerTime | 800 | 619.99 | 0.01 | 100.00

@JackCaoG @yaochengji I just parsed the above log. We observe that DeviceLockWait is taking around 30% of the time (assuming that most of these items are serial). Do you know if this is expected? Any other suggestions?

**Comment by JackCaoG** [comment]
It is expected, this is a metric I get when I run transformer on TPUVM

```
Metric: DeviceLockWait
  TotalSamples: 26930
  Accumulator: 03h46m03s589ms503.680us
  ValueRate: 810ms150.459us / second
  Rate: 2.88981 / second
  Percentiles: 1%=001.992us; 5%=105ms444.655us; 10%=110ms624.682us; 20%=117ms464.942us; 50%=393ms210.972us; 80%=410ms693.361us; 90%=413ms580.081us; 95%=414ms224.159us; 99%=434ms854.877us
Metric: ExecuteTime
  TotalSamples: 26119
  Accumulator: 03h19m07s454ms457.210us
  ValueRate: 965ms317.892us / second
  Rate: 2.7733 / second
  Percentiles: 1%=135ms779.346us; 5%=135ms127.637us; 10%=135ms265.125us; 20%=135ms498.381us; 50%=481ms591.205us; 80%=484ms992.992us; 90%=486ms560.143us; 95%=487ms979.286us; 99%=499ms331.881us
```

You see that `DeviceLockWait` often is a bit longer than the `ExecuteTime`. What happened was that pt/xla execution is async. Before the synchronous operations can start(fetch the actual value for example), they need to wait that the pending asynchronous operations have completed. If we want to start another async execution, we also need to wait for the previous one to finish. More to read in https://github.com/pytorch/xla/blob/08ae1044c2a7e314895f9946104cbe399e096515/torch_xla/csrc/tensor.cpp#L55

Looking at your metric, everything else seems fine. Compilation takes a long time but hopefully in the following epochs you don't need to recompile and only perform the execution.

Another thing to note is that metric does not record every event in your training. That means if you added up all of the times in your metric report, it won't equal to  the total training time.

**Comment by anijain2305** [comment]
Thanks @JackCaoG . We did a little more profiling and found that a lot of time goes in the forward and backward calls.

~~~
        outputs = model(input_ids, attention_mask=attention_mask,
                        labels=labels) # Considerable time spent In this line
        loss = outputs.loss



    if xla_enabled:
        scaler.scale(loss).backward()  # Considerable time spent In this line
        gradients = xm._fetch_gradients(optimizer)
        xm.all_reduce("sum", gradients, scale=1.0 / xm.xrt_world_size())
        scaler.step(optimizer)
        scaler.update()
        xm.mark_step()
~~~


I observed that in addition to XLA runtime, a lot of time is spent in these `fwd` and `bwd` python calls (highlighted by comments. I think during this time, we are building XLA graph. Do you know what is happening during this time? And is it possible to share the code path so that I can put timers and measure the overhead?

**Comment by JackCaoG** [comment]
@anijain2305 You can consider using https://github.com/pytorch/xla#-performance-profiling-and-auto-metrics-analysis to profile your runs. You should be able to see what happened during that time. I think it is just building the ir graph during forward and backward but it shouldn't take that long.

Also please open an new github issue since it is not related to the original topic.

**Comment by anijain2305** [comment]
Opened a new issue - https://github.com/pytorch/xla/issues/3043
